name: Deploy release build

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'The repo to push to'
        required: true
        default: tlang-wasm

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install wasm-pack
      run: cargo install wasm-pack
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.1.0
    - name: Cache node modules
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - run: npm install
    - name: Build release wasm
      working-directory: wasm
      run: npm run release
    - name: list the pkg
      run: ls -hl wasm/pkg
    # - name: Commit the release
    #   run: node tasks/deploy/index.js wasm/pkg
    #   env:
    #     ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
    #     REPO: ${{ github.event.inputs.repo }}

